name: CI for iOS 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install npm dependencies
        run: |
          cd ${{ github.workspace }}/ConnectedToCulture
          npm install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Bundler
        run: gem install bundler -v 2.4.22

      - name: Install CocoaPods
        run: |
          cd ${{ github.workspace }}/ConnectedToCulture/ios
          pod install
          pod --version

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: List Xcode Schemes
        run: |
          cd ${{ github.workspace }}/ConnectedToCulture/ios
          xcodebuild -list

      - name: Increment build number
        run: |
          cd ${{ github.workspace }}/ConnectedToCulture/ios
          agvtool new-version -all $(date +%Y%m%d%H%M)

      - name: Build app
        run: |
          cd ${{ github.workspace }}/ConnectedToCulture/ios
          ls -alh  # List files for debugging
          xcodebuild -workspace ConnectedToCulture.xcworkspace \
                      -scheme ConnectedToCulture \
                      -sdk iphoneos \
                      -configuration Release \
                      -archivePath ${{ github.workspace }}/build/ConnectedToCulture.xcarchive \
                      clean archive \
                      CODE_SIGN_IDENTITY="Apple Distribution: A Management Group Consulting LLC" \
                      PROVISIONING_PROFILE_SPECIFIER="ConnectedToCulture_C2C_Ad_Hoc" \
                      DEVELOPMENT_TEAM="24832U2HJT" \
                      OTHER_CODE_SIGN_FLAGS="--allowProvisioningUpdates"
          xcodebuild -exportArchive \
                      -archivePath ${{ github.workspace }}/build/ConnectedToCulture.xcarchive \
                      -exportOptionsPlist ${{ github.workspace }}/ConnectedToCulture/ios/exportOptions.plist \
                      -exportPath ${{ github.workspace }}/build

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: ${{ github.workspace }}/build/ConnectedToCulture.ipa

